name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    runs-on: macos-13
    timeout-minutes: 15
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - name: Git - Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.ref }}
      - name: Setup - Xcode
        run: sudo xcode-select -s /Applications/Xcode_14.3.app
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
